<?php
$_links = $this->getLinks();
if (count($_links)) {
    ?>
    <div class="block block-account">
        <div class="block-title">
            <strong><span><?php echo Mage::getStoreConfig('webforms/general/customer_navigation_block_title'); ?></span></strong>
        </div>
        <div class="block-content">
            <ul>
                <?php $_index = 1; ?>
                <?php $_count = count($_links); ?>
                <?php foreach ($_links as $_link): ?>
                    <?php $_last = ($_index++ >= $_count); ?>
                    <?php if ($_link->getActive()): ?>
                        <li class="current<?php echo($_last ? ' last' : '') ?>">
                            <strong><?php echo $_link->getLabel() ?></strong></li>
                    <?php else: ?>
                        <li<?php echo($_last ? ' class="last"' : '') ?>><a
                                href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php } ?>